In [1]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)

In [3]:
data

array([[-0.49586477, -0.14705545,  0.10763381],
       [-0.42072738,  1.00034885,  0.35340529]])

In [4]:
data = data * 10

In [5]:
data

array([[-4.95864771, -1.47055448,  1.07633811],
       [-4.2072738 , 10.00348846,  3.5340529 ]])

In [6]:
data + data

array([[-9.91729543, -2.94110897,  2.15267623],
       [-8.41454759, 20.00697693,  7.06810581]])

In [7]:
data.dtype

dtype('float64')

In [8]:
data.shape

(2, 3)

In [9]:
data1 = [1,2,3,4]
arr1 = np.array(data1)

In [10]:
arr1

array([1, 2, 3, 4])

In [18]:
data2 = [[2,3,4,5],[6,7,8,9]]
arr2 = np.array(data2)

In [19]:
arr2

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [20]:
arr2.dtype

dtype('int64')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])



![alt text](https://i.ibb.co/MfbDF08/Screenshot-2019-10-08-at-4-18-49-PM.png "Logo Title Text 1")


In [27]:
myarr = np.array([1,2,3],dtype=np.float64)
myarr

array([1., 2., 3.])

![alt text](https://i.ibb.co/mC7dW2Y/Screenshot-2019-10-08-at-4-22-44-PM.png "Logo Title Text 1")

## Casting

In [28]:
myarr = np.array([1,2,3,4,5])

In [31]:
myarr.dtype

dtype('int64')

In [32]:
float_arr = myarr.astype(np.float64)

In [33]:
float_arr.dtype

dtype('float64')

In [34]:
float_arr

array([1., 2., 3., 4., 5.])

In this example, integers were cast to floating point. If I cast some floating-point numbers to be of integer dtype, the decimal part will be truncated.
Calling astype always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype.

## Vectorization

Arrays are important because they enable you to express batch operations on data without writing any for loops. NumPy users call this vectorization. Any arithmetic operations between equal-size arrays applies the operation element-wise:

In [36]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [39]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
1/arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [38]:
arr1*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [54]:
arr1 + arr1

array([[ 2,  4,  6],
       [ 8, 10, 12]])

Like arithmetic operations, compari‐ sons (such as ==) with arrays are also vectorized.

In [55]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [56]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

Operations between differently sized arrays is called broadcasting

## Indexing and Slicing

NumPy array indexing is a rich topic, as there are many ways you may want to select a subset of your data or individual elements. One-dimensional arrays are simple; on the surface they act similarly to Python lists:

In [41]:
arr4 = np.array([9,8,7,6,5,4,3,2,1,0])

In [44]:
arr4[3:6]

array([6, 5, 4])

In [47]:
arr4[3:6] = 133

In [48]:
arr4

array([  9,   8,   7, 133, 133, 133,   3,   2,   1,   0])

As you can see, if you assign a scalar value to a slice, as in arr4[3:6] = 133, the value is propagated (or broadcasted henceforth) to the entire selection.

In [49]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [50]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [53]:
arr2d[2, 1:]

array([8, 9])

![alt text](https://i.ibb.co/Z2mfy0Y/Screenshot-2019-10-08-at-4-46-39-PM.png "Logo Title Text 1")